name: Manage Kustomize TCP/NodePort Ports

on:
  workflow_dispatch:
    inputs:
      patch_type:
        description: 'Type of patch to update (tcp or nodeport)'
        required: true
        type: choice
        options:
          - tcp
          - nodeport

      main_port:
        description: 'Main port number (host_port or node_port)'
        required: true
        type: string

      container_port:
        description: 'Target container port'
        required: true
        type: string

      namespace:
        description: 'Namespace (required only for tcp)'
        required: false
        type: string

      service:
        description: 'Service name (required only for tcp)'
        required: false
        type: string

      second_port:
        description: 'Second host/node port (optional)'
        required: false
        type: string

      second_container:
        description: 'Second container port (optional)'
        required: false
        type: string

      file:
        description: 'Path to kustomization.yaml file (relative to repo root)'
        required: false
        default: 'kustomization.yaml'
        type: string

      dry_run:
        description: 'Run in dry-run mode (only show changes, don't commit)'
        required: false
        type: boolean
        default: true

jobs:
  update-ports:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml

      - name: Prepare script
        run: |
          # If your script is already in the repository, you can skip this step
          # For demo purposes - you can remove this and just use your existing file
          cat > manage-ports.py << 'EOF'
          # Paste your complete python script here
          # .......................................
          # (the full script from previous messages)
          # .......................................
          EOF

      - name: Run port management script
        env:
          # Optional: if your script needs any environment variables
        run: |
          args=()

          args+=("${{ inputs.patch_type }}")
          args+=("${{ inputs.main_port }}")

          if [ "${{ inputs.patch_type }}" = "tcp" ]; then
            args+=("${{ inputs.namespace }}")
            args+=("${{ inputs.service }}")
            args+=("${{ inputs.container_port }}")
          else
            args+=("${{ inputs.container_port }}")
          fi

          if [ -n "${{ inputs.second_port }}" ] && [ -n "${{ inputs.second_container }}" ]; then
            args+=(--second "${{ inputs.second_port }}" "${{ inputs.second_container }}")
          fi

          if [ "${{ inputs.dry_run }}" = "true" ]; then
            args+=(--dry-run)
          fi

          if [ -n "${{ inputs.file }}" ] && [ "${{ inputs.file }}" != "kustomization.yaml" ]; then
            args+=(--file "${{ inputs.file }}")
          fi

          python manage-ports.py "${args[@]}"

      # ── Only commit & push if not dry-run ─────────────────────────────────────
      - name: Commit changes (if not dry-run)
        if: ${{ !inputs.dry_run }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add ${{ inputs.file }}
          git diff --staged --quiet || git commit -m "chore(ports): update ${inputs.patch_type} ports (${inputs.main_port})"
          git push

      - name: Show result message
        run: |
          echo ""
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "Dry run completed - no changes were committed."
          else
            echo "Changes committed and pushed successfully."
          fi
