name: Update Kustomize Ports → Create PR

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'Upstream repository (owner/repo format)'
        required: true
        type: string
        # example: company/dremio-platform

      branch_name:
        description: 'Name of the new branch to create'
        required: true
        type: string
        default: update-tcp-ports-${{ github.run_id }}

      kustomization_path:
        description: 'Path to kustomization.yaml file (relative to repo root)'
        required: true
        type: string
        default: kustomization.yaml

      patch_type:
        description: 'tcp or nodeport'
        required: true
        type: choice
        options:
          - tcp
          - nodeport

      main_port:
        description: 'Main port (host_port / node_port)'
        required: true
        type: string

      container_port:
        description: 'Target container port'
        required: true
        type: string

      namespace:
        description: 'Namespace (required only for tcp)'
        required: false
        type: string

      service:
        description: 'Service name (required only for tcp)'
        required: false
        type: string

      second_port:
        description: 'Second port (optional)'
        required: false
        type: string

      second_container:
        description: 'Second container port (optional)'
        required: false
        type: string

      pr_title:
        description: 'Title of the created Pull Request'
        required: false
        default: 'chore(ports): update ${{ inputs.patch_type }} ports (${{ inputs.main_port }})'
        type: string

      pr_body:
        description: 'Body of the PR (markdown)'
        required: false
        default: |
          Automated update of TCP/NodePort mappings using port-management script.

          **Changes:**
          - ${{ inputs.patch_type }}: added/updated port ${{ inputs.main_port }}
          - File: ${{ inputs.kustomization_path }}
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Show inputs (debug)
        run: |
          echo "Upstream repo: ${{ inputs.upstream_repo }}"
          echo "Branch:       ${{ inputs.branch_name }}"
          echo "File:         ${{ inputs.kustomization_path }}"
          echo "Type:         ${{ inputs.patch_type }}"
          echo "Main port:    ${{ inputs.main_port }}"

      - name: Checkout fork (or create fork if needed)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          path: fork

      # ── Fork the upstream repo if we're not already in a fork ────────────────
      - name: Check if we need to fork upstream
        id: check_fork
        run: |
          UPSTREAM_OWNER=$(echo "${{ inputs.upstream_repo }}" | cut -d'/' -f1)
          UPSTREAM_REPO=$(echo "${{ inputs.upstream_repo }}" | cut -d'/' -f2)

          gh repo fork "$UPSTREAM_OWNER/$UPSTREAM_REPO" --remote=false --org "${{ github.repository_owner }}" || true
          echo "forked_repo=$UPSTREAM_OWNER-${UPSTREAM_REPO}-fork" >> "$GITHUB_OUTPUT"

      - name: Checkout forked repository
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.check_fork.outputs.forked_repo || github.repository }}
          path: workspace
          ref: main

      - name: Create and checkout new branch
        working-directory: workspace
        run: |
          git checkout -b "${{ inputs.branch_name }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install ruamel.yaml

      - name: Run port management script
        working-directory: workspace
        env:
          SCRIPT_PATH: manage-ports.py
        run: |
          # If script is not already in repo, create it here (or assume it's present)
          # In real workflow you'd probably commit the script to your fork/repo

          python "${SCRIPT_PATH}" \
            "${{ inputs.patch_type }}" \
            "${{ inputs.main_port }}" \
            ${{ inputs.patch_type == 'tcp' && format('"{0}" "{1}" {2}', inputs.namespace, inputs.service, inputs.container_port) || inputs.container_port }} \
            ${{ inputs.second_port && format('--second {0} {1}', inputs.second_port, inputs.second_container) || '' }} \
            --file "${{ inputs.kustomization_path }}" \
            --dry-run false

      - name: Commit and push changes
        working-directory: workspace
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add "${{ inputs.kustomization_path }}"
          git commit -m "${{ inputs.pr_title }}" || echo "No changes to commit"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ inputs.pr_title }}"
          title: "${{ inputs.pr_title }}"
          body: "${{ inputs.pr_body }}"
          base: main
          branch: "${{ inputs.branch_name }}"
          delete-branch: true
          labels: |
            automerge
            ports-update
          reviewers: |
            ${{ github.actor }}
